import { useState } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Link2, Copy, Plus } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';

export default function LGDashboard() {
    const [caName, setCaName] = useState('');
    const { toast } = useToast();

    // Mock data for reporting
    const links = [
        { id: 1, caName: 'Rahul Kumar', url: 'https://leadcubed.in/form/rahul-kumar', leads: 45, interested: 12, paid: 5, revenue: '₹25,000', projected: '₹60,000' },
        { id: 2, caName: 'Priya Singh', url: 'https://leadcubed.in/form/priya-singh', leads: 32, interested: 8, paid: 3, revenue: '₹15,000', projected: '₹40,000' },
        { id: 3, caName: 'Amit Patel', url: 'https://leadcubed.in/form/amit-patel', leads: 28, interested: 15, paid: 8, revenue: '₹40,000', projected: '₹75,000' },
    ];

    const handleCreateLink = () => {
        if (!caName) return;
        toast({
            title: "Link Created",
            description: `Public form link created for ${caName}`,
        });
        setCaName('');
    };

    const copyLink = (url: string) => {
        navigator.clipboard.writeText(url);
        toast({
            title: "Copied",
            description: "Link copied to clipboard",
        });
    };

    return (
        <DashboardLayout>
            <div className="p-8 space-y-8">
                <div>
                    <h1 className="text-2xl font-bold mb-2">Lead Generation Dashboard</h1>
                    <p className="text-muted-foreground">Manage public form links and track performance.</p>
                </div>

                {/* Create Link Section */}
                <Card className="glass">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Link2 className="h-5 w-5 text-primary" />
                            Create Public Link
                        </CardTitle>
                        <CardDescription>Generate a unique lead form link for a Campus Ambassador (CA).</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div className="flex gap-4 max-w-md">
                            <Input
                                placeholder="Enter CA Name"
                                value={caName}
                                onChange={(e) => setCaName(e.target.value)}
                            />
                            <Button onClick={handleCreateLink} className="gradient-primary">
                                <Plus className="h-4 w-4 mr-2" />
                                Generate Link
                            </Button>
                        </div>
                    </CardContent>
                </Card>

                {/* Reporting Table */}
                <Card className="glass">
                    <CardHeader>
                        <CardTitle>Link Performance</CardTitle>
                        <CardDescription>Track leads and revenue generated by each link.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead>CA Name</TableHead>
                                    <TableHead>Link URL</TableHead>
                                    <TableHead className="text-right">Total Leads</TableHead>
                                    <TableHead className="text-right">Interested</TableHead>
                                    <TableHead className="text-right">Paid</TableHead>
                                    <TableHead className="text-right">Revenue Received</TableHead>
                                    <TableHead className="text-right">Revenue Projected</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {links.map((link) => (
                                    <TableRow key={link.id}>
                                        <TableCell className="font-medium">{link.caName}</TableCell>
                                        <TableCell>
                                            <div className="flex items-center gap-2">
                                                <span className="text-sm text-muted-foreground truncate max-w-[200px]">{link.url}</span>
                                                <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => copyLink(link.url)}>
                                                    <Copy className="h-3 w-3" />
                                                </Button>
                                            </div>
                                        </TableCell>
                                        <TableCell className="text-right">{link.leads}</TableCell>
                                        <TableCell className="text-right">{link.interested}</TableCell>
                                        <TableCell className="text-right">{link.paid}</TableCell>
                                        <TableCell className="text-right text-success font-medium">{link.revenue}</TableCell>
                                        <TableCell className="text-right text-muted-foreground">{link.projected}</TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </CardContent>
                </Card>
            </div>
        </DashboardLayout>
    );
}
